### ISSUE TITLE
Integrate Lucene / Disable OpenNER

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#171]
Problem to address: We're using OPenNER for our NLP solution for keyword and place detection in Fortis. Through running the pipeline in high volume scenarios, we're noticing the performance of OPenNER ranging anywhere from ~100 - 500ms per event. This is causing the batch runtime to exceed the spark streaming interval, hence fortis crashing after an hour. 

Solution: We decided to integrate Lucene as our in-memory search engine for detecting mentioned keywords / places. 

*Implementation* 
- Add the 3 Lucene core jars dependencies into the Fortis build. 
- Index initial `DStream` pipeline events in Lucene.
- Build the 2 Lucene search queries off of the geofenced list of places and the watchlist keyword terms. The keyword search should support terms across all supported languages. We should leverage the 30+ available language models that come pre-packaged through Lucene https://lucene.apache.org/core/7_0_0/analyzers-common/index.html .
- The results of the Lucene index search should be ranked on search relevancy, weighted by mention count.

**Comment by c-w** [comment]
Note that Lucene doesn't seem to contain NLP capabilities like Named-Entity Recognition ([source](https://stackoverflow.com/q/4308132/3817588)) so the results for complex tasks like extracting places may be poorer than via OpeNER since we'll just rely on word match instead of also using statistical/machine-learning features. To my understanding, the analyzers (e.g. [for CJK languages](https://lucene.apache.org/core/7_0_0/analyzers-common/org/apache/lucene/analysis/cjk/package-summary.html)) are just concerned with taking a text string and converting it into a word vector.

**Comment by c-w** [comment]
Looks like this was implemented in [LuceneLocationsExtractor](https://github.com/CatalystCode/project-fortis/blob/39b7634225ea14e8addc163dff91c781fd83d794/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/locations/LuceneLocationsExtractor.scala) and [LuceneLocationsExtractor](https://github.com/CatalystCode/project-fortis/blob/39b7634225ea14e8addc163dff91c781fd83d794/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/locations/LuceneLocationsExtractor.scala).
