### ISSUE TITLE
Spark Pipeline - Integrate Cassandra Site Config Schema with Spark Filter

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-spark#6]
This task encompasses the following features.

Implement the Spark integration with the site configuration definition sourced from Cassandra. 

The site definition covers the following categories.
   - Topic Whitelist
   - Topic Blacklist
   - The geofence defined in the fortis site config
   -  Facebook pagelist
   - Trusted twitter profile

The Topic whitelist should be used for the Facebook, Twitter, Bing and Instagram data connector filters. The geofence should be used for the Facebook, Twitter and Instagram data streaming connector. We need to utilize broadcast variables to help keep the site configuration data structures in Spark synchronized when they're modified in the admin screen of fortis. 

The filter will need to be re-applied following the completion of the feature extraction processing.

**Comment by kevinhartman** [comment]
**Done**
- [X] Add main data layer models and Cassandra client schema models for configuration objects (tables).
- [x] Add an interface for reading/populating configuration models from any data store. 
  - We will need an implementation of this interface for Cassandra (#42).

**In progress**
- [x] Create shared `TransformManager` which will hold transform utility instances (wrapped in `Broadcast[T]` where applicable), and update those utilities from Cassandra. This class will know the last time tools were updated, and only fetch when its `.update()` method is called **AND** the elapsed time since the last update is larger than the configuration update window.
